source-file ~/.config/tmux/tmux.reset.conf

set -g history-limit 5000     # increase history size (from 2,000)
set -a terminal-features "tmux-256color:RGB"
set -g base-index 1
set -g renumber-windows on
set -g mode-keys vi

# BEGIN Omarchy managed tmux theme
if-shell -b 'test -f "/home/mark/.config/omarchy/current/theme/tmux.conf"' 'source-file "/home/mark/.config/omarchy/current/theme/tmux.conf"'
# END Omarchy managed tmux theme
